### ISSUE TITLE
Installation guide for non windows developers

### ISSUE THREAD

**Issue by rgeber** [koesie10/fsuipc-node#1]
Hi

I'm struggling to install the package as it does require compilers, etc. As a Unix guy my Windows development know how is little at best. Please forgive me if I'm asking some very basic questions here.

I've installed Python 2.7.15 (x64), Visual Studio CE 2017 and the `windows-build-tools` package via `npm`. When I try to run `npm install --save fsuipc` I get this output:

```
# npm install --save fsuipc

> fsuipc@0.2.1 install E:\tmp\node_test\node_modules\fsuipc
> node-gyp rebuild


rgeber@VELOCITY E:\tmp\node_test\node_modules\fsuipc
# if not defined npm_config_node_gyp (node "E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
E:\tmp\node_test\node_modules\fsuipc\build\fsuipc.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on  disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\dev_tools\\node-v8.11.3-win-x64\\node.exe" "E:\\dev_tools\\node-v8.11.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\tmp\node_test\node_modules\fsuipc
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node_test@1.0.0 No description
npm WARN node_test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsuipc@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsuipc@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rgeber\AppData\Roaming\npm-cache\_logs\2018-08-14T12_26_48_030Z-debug.log
```

The log file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\dev_tools\\node-v8.11.3-win-x64\\node.exe',
1 verbose cli   'E:\\dev_tools\\node-v8.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'fsuipc' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session fb82e53244c8724d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/fsuipc 220ms (from cache)
8 silly pacote tag manifest for fsuipc@latest fetched in 239ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule fsuipc@0.2.1 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bindings 56ms (from cache)
15 silly pacote range manifest for bindings@^1.3.0 fetched in 57ms
16 silly resolveWithNewModule bindings@1.3.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/nan 114ms (from cache)
18 silly pacote range manifest for nan@^2.8.0 fetched in 115ms
19 silly resolveWithNewModule nan@2.10.0 checking installable status
20 silly currentTree node_test@1.0.0
21 silly idealTree node_test@1.0.0
21 silly idealTree +-- bindings@1.3.0
21 silly idealTree +-- fsuipc@0.2.1
21 silly idealTree `-- nan@2.10.0
22 silly install generateActionsToTake
23 silly diffTrees action count 3
24 silly diffTrees add bindings@1.3.0
25 silly diffTrees add nan@2.10.0
26 silly diffTrees add fsuipc@0.2.1
27 silly decomposeActions action count 24
28 silly decomposeActions fetch bindings@1.3.0
29 silly decomposeActions extract bindings@1.3.0
30 silly decomposeActions preinstall bindings@1.3.0
31 silly decomposeActions build bindings@1.3.0
32 silly decomposeActions install bindings@1.3.0
33 silly decomposeActions postinstall bindings@1.3.0
34 silly decomposeActions finalize bindings@1.3.0
35 silly decomposeActions refresh-package-json bindings@1.3.0
36 silly decomposeActions fetch nan@2.10.0
37 silly decomposeActions extract nan@2.10.0
38 silly decomposeActions preinstall nan@2.10.0
39 silly decomposeActions build nan@2.10.0
40 silly decomposeActions install nan@2.10.0
41 silly decomposeActions postinstall nan@2.10.0
42 silly decomposeActions finalize nan@2.10.0
43 silly decomposeActions refresh-package-json nan@2.10.0
44 silly decomposeActions fetch fsuipc@0.2.1
45 silly decomposeActions extract fsuipc@0.2.1
46 silly decomposeActions preinstall fsuipc@0.2.1
47 silly decomposeActions build fsuipc@0.2.1
48 silly decomposeActions install fsuipc@0.2.1
49 silly decomposeActions postinstall fsuipc@0.2.1
50 silly decomposeActions finalize fsuipc@0.2.1
51 silly decomposeActions refresh-package-json fsuipc@0.2.1
52 silly install executeActions
53 silly doSerial global-install 24
54 verbose correctMkdir C:\Users\rgeber\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
55 verbose lock using C:\Users\rgeber\AppData\Roaming\npm-cache\_locks\staging-1555002a4bfe1919.lock for E:\tmp\node_test\node_modules\.staging
56 silly doParallel extract 24
57 silly extract bindings@1.3.0
58 silly pacote trying bindings@https://registry.npmjs.org/bindings/-/bindings-1.3.0.tgz by hash: sha512-DpLh5EzMR2kzvX1KIlVC0VkC3iZtHKTgdtZ0a3pglBZdaQFjt5S9g9xd1lE+YvXyfd6mtCeRnrUfOLYiTMlNSw==
59 silly extract nan@2.10.0
60 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.10.0.tgz by hash: sha512-bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA==
61 silly extract fsuipc@0.2.1
62 silly pacote trying fsuipc@https://registry.npmjs.org/fsuipc/-/fsuipc-0.2.1.tgz by hash: sha1-ieCqRqMtjASX8jptrJq53D/7yZ0=
63 silly pacote bindings@https://registry.npmjs.org/bindings/-/bindings-1.3.0.tgz extracted to E:\tmp\node_test\node_modules\.staging\bindings-64030c88 by content address 31ms
64 silly pacote fsuipc@https://registry.npmjs.org/fsuipc/-/fsuipc-0.2.1.tgz extracted to E:\tmp\node_test\node_modules\.staging\fsuipc-4e358ed7 by content address 329ms
65 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.10.0.tgz extracted to E:\tmp\node_test\node_modules\.staging\nan-769371bd by content address 333ms
66 silly doReverseSerial unbuild 24
67 silly doSerial remove 24
68 silly doSerial move 24
69 silly doSerial finalize 24
70 silly finalize E:\tmp\node_test\node_modules\bindings
71 silly finalize E:\tmp\node_test\node_modules\nan
72 silly finalize E:\tmp\node_test\node_modules\fsuipc
73 silly doParallel refresh-package-json 24
74 silly refresh-package-json E:\tmp\node_test\node_modules\bindings
75 silly refresh-package-json E:\tmp\node_test\node_modules\nan
76 silly refresh-package-json E:\tmp\node_test\node_modules\fsuipc
77 silly doParallel preinstall 24
78 silly preinstall bindings@1.3.0
79 info lifecycle bindings@1.3.0~preinstall: bindings@1.3.0
80 silly preinstall nan@2.10.0
81 info lifecycle nan@2.10.0~preinstall: nan@2.10.0
82 silly preinstall fsuipc@0.2.1
83 info lifecycle fsuipc@0.2.1~preinstall: fsuipc@0.2.1
84 silly doSerial build 24
85 silly build bindings@1.3.0
86 info linkStuff bindings@1.3.0
87 silly linkStuff bindings@1.3.0 has E:\tmp\node_test\node_modules as its parent node_modules
88 verbose linkBins bindings@1.3.0
89 verbose linkMans bindings@1.3.0
90 silly build nan@2.10.0
91 info linkStuff nan@2.10.0
92 silly linkStuff nan@2.10.0 has E:\tmp\node_test\node_modules as its parent node_modules
93 verbose linkBins nan@2.10.0
94 verbose linkMans nan@2.10.0
95 silly build fsuipc@0.2.1
96 info linkStuff fsuipc@0.2.1
97 silly linkStuff fsuipc@0.2.1 has E:\tmp\node_test\node_modules as its parent node_modules
98 verbose linkBins fsuipc@0.2.1
99 verbose linkMans fsuipc@0.2.1
100 silly doSerial global-link 24
101 silly doParallel update-linked 24
102 silly doSerial install 24
103 silly install bindings@1.3.0
104 info lifecycle bindings@1.3.0~install: bindings@1.3.0
105 silly install nan@2.10.0
106 info lifecycle nan@2.10.0~install: nan@2.10.0
107 silly install fsuipc@0.2.1
108 info lifecycle fsuipc@0.2.1~install: fsuipc@0.2.1
109 verbose lifecycle fsuipc@0.2.1~install: unsafe-perm in lifecycle true
110 verbose lifecycle fsuipc@0.2.1~install: PATH: E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\tmp\node_test\node_modules\fsuipc\node_modules\.bin;E:\tmp\node_test\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;E:\dev_tools\python_2715\;E:\dev_tools\python_2715\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\dotnet\;C:\Users\rgeber\AppData\Local\Microsoft\WindowsApps;C:\Users\rgeber\AppData\Local\atom\bin;E:\dev_tools\node-v8.11.3-win-x64
111 verbose lifecycle fsuipc@0.2.1~install: CWD: E:\tmp\node_test\node_modules\fsuipc
112 silly lifecycle fsuipc@0.2.1~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
113 silly lifecycle fsuipc@0.2.1~install: Returned: code: 1  signal: null
114 info lifecycle fsuipc@0.2.1~install: Failed to exec install script
115 verbose unlock done using C:\Users\rgeber\AppData\Roaming\npm-cache\_locks\staging-1555002a4bfe1919.lock for E:\tmp\node_test\node_modules\.staging
116 silly saveTree node_test@1.0.0
116 silly saveTree `-- fsuipc@0.2.1
116 silly saveTree   +-- bindings@1.3.0
116 silly saveTree   `-- nan@2.10.0
117 warn node_test@1.0.0 No description
118 warn node_test@1.0.0 No repository field.
119 verbose stack Error: fsuipc@0.2.1 install: `node-gyp rebuild`
119 verbose stack Exit status 1
119 verbose stack     at EventEmitter.<anonymous> (E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
119 verbose stack     at emitTwo (events.js:126:13)
119 verbose stack     at EventEmitter.emit (events.js:214:7)
119 verbose stack     at ChildProcess.<anonymous> (E:\dev_tools\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
119 verbose stack     at emitTwo (events.js:126:13)
119 verbose stack     at ChildProcess.emit (events.js:214:7)
119 verbose stack     at maybeClose (internal/child_process.js:925:16)
119 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
120 verbose pkgid fsuipc@0.2.1
121 verbose cwd E:\tmp\node_test
122 verbose Windows_NT 10.0.17134
123 verbose argv "E:\\dev_tools\\node-v8.11.3-win-x64\\node.exe" "E:\\dev_tools\\node-v8.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "fsuipc"
124 verbose node v8.11.3
125 verbose npm  v5.6.0
126 error code ELIFECYCLE
127 error errno 1
128 error fsuipc@0.2.1 install: `node-gyp rebuild`
128 error Exit status 1
129 error Failed at the fsuipc@0.2.1 install script.
129 error This is probably not a problem with npm. There is likely additional logging output above.
130 verbose exit [ 1, true ]
```

Could you please provide some kind of installation guide on how to compile the module?

Thanks

Roman

**Comment by BossOfGames** [comment]
You cannot compile FSUIPC unless it's on Windows due to the api calls. If you're developing on anything other than windows, include the package as a `optionalDependency`
